name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  rust:
    strategy:
      fail-fast: false
      matrix:
        version: [stable, beta, nightly]
    name: rust ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install test dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev xvfb
      - run: rustup default ${{ matrix.version }}
      - run: xvfb-run -a cargo test --all
